[env:esp32-wroom-32e]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
board_build.partitions = huge_app.csv

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BLUEDROID_ENABLED=1
    -DCONFIG_CLASSIC_BT_ENABLED=1

lib_deps =
    jgromes/RadioLib
    mikalhart/TinyGPSPlus
    pschatzmann/ESP32-A2DP
    sparkfun/SparkFun_WM8960_Arduino_Library
