[env:esp32-s3-wroom-1]
platform = espressif32 @ 6.13.0
board = esp32-s3-devkitc-1
framework = arduino, espidf
monitor_speed = 115200
extra_scripts = pre:tools/provision-web-tls.py
upload_speed = 921600
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16711680
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.f_cpu = 240000000L
board_build.partitions = no_ota.csv

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM
    -DFIELD_RADIO_ESP32_S3_WROOM_1_N16R8

lib_deps =
    jgromes/RadioLib@^7.7.1
    mikalhart/TinyGPSPlus
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit NeoPixel
    h2zero/NimBLE-Arduino@^2.5.1
    https://github.com/jackjansen/esp32_idf5_https_server_compat.git
