[env:esp32-c3-devkitm-1]
platform = espressif32 @ 6.13.0
platform_packages =
    platformio/espressif32 @ 6.13.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -I../shared
    -DSENSOR_NODE_ESP32C3
; ---- PINNED DEPENDENCIES ----
lib_deps =
    h2zero/NimBLE-Arduino@^2.5.1
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.15
