#pragma once
#include <Arduino.h>
#include <ESPWebServerSecure.hpp>
#include <FS.h>
#include <IPAddress.h>

class WebUi {
public:
  explicit WebUi(ESPWebServerSecure& server) : server_(server) {}
  void begin();
  void task();
private:
  ESPWebServerSecure& server_;
  bool auth();
  bool sameOrigin();
  uint32_t authFailureWindowStartMs_ = 0;
  uint8_t authFailures_ = 0;
  uint32_t authFailureWindowCount_ = 0;
  uint32_t authBlockedUntilMs_ = 0;
  struct AuthThrottleEntry {
    String ip;
    uint32_t windowStartMs = 0;
    uint32_t blockedUntilMs = 0;
    uint8_t failures = 0;
    uint32_t lastSeenMs = 0;
  };
  static constexpr size_t AUTH_THROTTLE_ENTRIES = 16;
  AuthThrottleEntry authThrottle_[AUTH_THROTTLE_ENTRIES]{};
  uint32_t csrfFailures_ = 0;
  // ENH-1: Up to four independent browser sessions are retained in RAM.
  struct SessionSlot {
    uint8_t secret[32] = {};
    uint8_t csrf[16] = {};
    uint32_t issuedMs = 0;
    uint32_t clientIp = 0;
    bool inUse = false;
  };
  static constexpr size_t MAX_SESSIONS = 4;
  SessionSlot sessions_[MAX_SESSIONS]{};
  int8_t activeSessionSlot_ = -1;
  uint32_t lastMessageMs_ = 0;
  uint32_t lastSosMs_ = 0;
  uint32_t lastPttMs_ = 0;
  uint32_t lastConfigMs_ = 0;
  uint32_t lastSensorNodesMs_ = 0;
  uint32_t lastSensorLiveMs_ = 0;
  uint32_t lastSensorActionMs_ = 0;
  uint32_t lastBlePasskeyMs_ = 0;
  uint32_t lastSensorQueuePolicyMs_ = 0;
  File uploadFile_;
  String uploadPath_;
  size_t uploadBytes_ = 0;
  bool uploadFailed_ = false;
  uint64_t recordScheduleStart_ = 0;
  uint32_t recordScheduleDurationSec_ = 0;
  bool recordScheduleActive_ = false;
  uint32_t selfTestMs_ = 0;
  String selfTestResult_;
  void handleRoot();
  void handleStatus();
  void handleLoRaWANStatus();
  void handleLoRaWANConnect();
  void handleLoRaWANDisconnect();
  void handleLoRaWANConfig();
  void handleLoRaWANUplink();
  void handleApiVersion();
  void handleFiles();
  void handleDownload();
  void handleUpload();
  void handleRename();
  void handleMessages();
  void handleMessagePersist();
  void handleMessageSchedule();
  void handleMessageScheduleList();
  void handleMessageScheduleDelete();
  void handleRecordSchedule();
  void handleRecordScheduleGet();
  void handleSosFormat();
  void handleSelfTest();
  void handleSelfTestResult();
  void handleLang();
  void handleNeighbors();
  void handleRoutes();
  void handleCaptureStart();
  void handleCaptureStop();
  void handleCaptureDump();
  void handleAdr();
  void handleHopSync();
  void handleDedupStats();
  void handleTheme();
  void handleNvs();
  void handleConfigMigrate();
  void handleBatteryHistory();
  void handleMessageClear();
  void handleMessageRead();
  void handleMessageReply();
  void handleMessageExport();
  void handleRadioHistory();
  void handleRadioTune();
  void handleStorageInfo();
  void handleChecksum();
  void handleSosHistory();
  void handleLoraLog();
  void handleHealthLog();
  void handleBatteryCalibrate();
  void handleMessage();
  void handleSos();
  void handleSosStatus();
  void handleScanStatus();
  void handleScanStart();
  void handleScanStop();
  void handleScanResults();
  void handleHopSuggest();
  void handleHopStatus();
  void handleHopEnable();
  void handlePtt();
  void handleRecord();
  void handlePlay();
  void handleStop();
  void handlePause();
  void handleSeek();
  void handleQueue();
  void handleQueueClear();
  void handleRecordPause();
  void handleRecordSplit();
  void handleVox();
  void handleVad();
  void handleRecordQuality();
  void handleUsbTransport();
  void handleVolume();
  void handleDelete();
  void handleTrack();
  void handleTrackPoints();
  void handleTrackSimplified();
  void handleTrackDownload();
  void handleRadioStats();
  void handleRfDetector();
  void handleRangeTest();
  void handleRangeTestStatus();
  void handleHopSetChannels();
  void handleReboot();
  bool rateLimit(uint32_t& last, uint32_t interval);
  bool sessionValid();
  bool csrfValid();
  bool issueSession();
  String csrfTokenHexForActiveSession() const;
  int findSessionSlot(const uint8_t token[32], uint32_t clientIp) const;
  void auditAuth(bool success);
  void handleConfig();
  void handleConfigExport();
  void handleConfigBackup();
  void handleConfigRestore();
  void handleFactoryReset();
  void handleAudioSource();
  void handleChecksumSha256();
  void handleLogExport();
  void handleForwardStats();
  void handleAuthStats();
  void handleSensorNodes();
  void handleSensorNodeDetail();
  void handleSensorLive();
  void handleSensorForget();
  void handleSensorRefresh();
  void handleBlePasskeySet();
  void handleBlePasskeyDelete();
  void handleBlePasskeyList();
  void handleSensorQueuePolicy();
  void handleSensorDedupStats();
  void handleSensorSpool();
  void handleSensorSpoolClear();
  void handleDiagFull();
};
